### ISSUE TITLE
'Nan' displayed on click

### ISSUE THREAD

**Issue by Kraymer** [ColinEberhardt/applause-button#11]
Here how it looks after I click the button on project page :

![image](https://user-images.githubusercontent.com/84227/45344353-d1dcb800-b5a3-11e8-977c-5ae63beea28c.png)

**Comment by ColinEberhardt** [comment]
Oh wow, thanks for pointing out. I've just spotted the issue, when the clap count is >1000 the comma separator breaks the parsing logic. I'll get this fixed shortly.
