### ISSUE TITLE
Specific Instructions

### ISSUE THREAD

**Issue by moneymustard** [ColinEberhardt/applause-button#13]
Looking for more specific instructions to help me out, as a novice developer.

Going from [the site](https://applause-button.com/) here. Have a few questions about each step.

What specifically do I do with the distribution files after downloading?

Where do I include the Applause button JavaScript and stylesheet on my page if I want the button to appear site-wide?

When you say "then add the applause-button element" in Step 2, where do you add it? Also, what is its nomenclature to look for?

Thanks for the help

**Comment by ColinEberhardt** [comment]
Hi @moneymustard - I'll see if I can help out ...

> What specifically do I do with the distribution files after downloading?

You place the CSS and JS files on your webserver, and reference them in your HTML files as follows:

~~~
<head>
  <link rel="stylesheet" href="applause-button.css" />
  <script src="applause-button.js"></script>
</head>
~~~

> Where do I include the Applause button JavaScript and stylesheet on my page if I want the button to appear site-wide?

I'm afraid this really depends on the way your site is constructed. Is it a Wordpress site? If so, you should have theme files that allow you to make site-wide changes.

> When you say "then add the applause-button element" in Step 2, where do you add it? Also, what is its nomenclature to look for?

Where you add the element is up to you - and will dictate where it appears from a user perspective. Feel free to experiment!
