### ISSUE TITLE
Would be nice to have demo button on the website

### ISSUE THREAD

**Issue by greybax** [ColinEberhardt/applause-button#14]
Now https://applause-button.com/ has only images and code snippet for integrating button on your app. 
But I think it would be nice to have demo button on website itself.

**Comment by ColinEberhardt** [comment]
Hi @greybax it might not be obvious, but that great big button at the top of the page:

![image](https://user-images.githubusercontent.com/1098110/46733911-9bb95380-cc89-11e8-8962-da4d436032a3.png)

It's real - click it :-)
