### ISSUE TITLE
jumps by ~6 on each click

### ISSUE THREAD

**Issue by glendeni** [ColinEberhardt/applause-button#15]
On my webpage a click shows the count increasing by one as expected, but a refresh of the webpage, or as later viewed by another browser/user, shows a count mysteriously increased by ~6-7 !? Occurs both for tests by myself and comparing apache logging of clicks by outsiders (using an “onclick” logging to get my own count) and using different browsers.  Website is AMS EC2, clock accurate to within 1 sec.

**Comment by ColinEberhardt** [comment]
Fixed this a while back. I was experimenting with a slightly over complicated mechanism for preventing DOS style attacks
