### ISSUE TITLE
big number of applauses

### ISSUE THREAD

**Issue by achopijocoder** [ColinEberhardt/applause-button#17]
When a number of applauses is very big (like 234234234234234234234) it is not well centered

**Comment by ColinEberhardt** [comment]
Wow, you must have a very popular blog!

I see the issue ...

![image](https://user-images.githubusercontent.com/1098110/49512827-013f5000-f887-11e8-8348-f031344ffbc3.png)

**Comment by achopijocoder** [comment]
Well, not popular at all.
Just need to cover all the possible behaviors.
