### ISSUE TITLE
multiclap count not updating properly

### ISSUE THREAD

**Issue by spadesberry** [ColinEberhardt/applause-button#18]
It does not seem to save multiclaps. i added the multiclap="true" but it only saves one.

**Comment by ColinEberhardt** [comment]
Are you using an up-to-date version of the library? I made a few changes in v3.0.0 to prevent DOS attacks. As a result, older versions of the library no longer support multi-clap:

https://github.com/ColinEberhardt/applause-button/releases/tag/v3.0.0

Can you Try updating, and see if it works OK for you?

**Comment by spadesberry** [comment]
Thanks for you time. its worked 👍
