### ISSUE TITLE
Find a way to update the version number in code

### ISSUE THREAD

**Issue by ColinEberhardt** [ColinEberhardt/applause-button#26]
Currently version numbers are managed by semantic release, however, I'd like to have it [in the code too](https://github.com/ColinEberhardt/applause-button/blob/master/src/applause-button.js#L3) so that I can log client version information

**Comment by chriswilty** [comment]
This is addressed in a branch on my fork, using rollup's replace plugin:
https://github.com/chriswilty/applause-button/compare/feature/a11y...chriswilty:applause-button:chore/package-version
