### ISSUE TITLE
multiclap count not updating properly v3.3.0

### ISSUE THREAD

**Issue by jn8029** [ColinEberhardt/applause-button#28]
Hi,

V3.3.0
test url:  https://warrencheng.dev/linked-list-cpp-malloc/

multiclap attribute is set to 'true', and the button does allow multiclaps. but the clap count is not updated after you refresh the page.

**Comment by ColinEberhardt** [comment]
Hi @jn8029 - I've just tested your page above, and multiclap is working.

What you're probably encountering is the server-side DOS / spam protection. Multiple requests to update a clap count from the same IP address are ignored. Before I implemented that feature, you wouldn't believe how many times I found people hammering the API to create an artificially inflated clap count for their pages!

**Comment by jn8029** [comment]
Hi @ColinEberhardt ,

Noted. Thank you for the prompt response.

**Comment by batzner** [comment]
> What you're probably encountering is the server-side DOS / spam protection. Multiple requests to update a clap count from the same IP address are ignored. Before I implemented that feature, you wouldn't believe how many times I found people hammering the API to create an artificially inflated clap count for their pages!

It might be helpful to include this info somewhere in the docs. I just added the applause button to my site (thank you for this great project!) and wanted to test it with a random url, but was confused by the clap count being stuck at 1. Nevertheless, I love the fact that you even added DOS / spam protection, as I was worried of people spamming the applause counts on my blog posts!
