### ISSUE TITLE
After clicking applause, counter number flashes on the screen on the far right

### ISSUE THREAD

**Issue by tiadaguru** [ColinEberhardt/applause-button#39]
First, thank you so much for this amazing tool: easy to use, easy to implement, responsive, scalable, fast, and...offering it for free? Once we can test it out a bit more, we'll absolutely be donating to cover server costs and as a big thank you. You've made sharing gratitude easy.

Just wanted to note a quick bug:

### Steps to Reproduce:

1. Open https://applause-button.com
2. Click the main Applause Button at the top.

### What happens:

1. The old count number flashes briefly on the right side of the screen.
2. The Button increments +1

I made a quick screen capture of what this looks like: https://streamable.com/o4f4a

### What should happen:

1. The Button increments +1

It also reproduces on [our test page here](https://tiadaguru.webflow.io/wall-of-hope).

Test environment:

- **confirmed in Google Chrome** in incognito mode // 80.0.3987.100 (64-bit)
- **confirmed in Mozilla Firefox** in a private window // 73.0 (64-bit)
- **confirmed in Microsoft Edge Legacy** in an InPrivate window // 44.18362.449.0
- Windows 10 Pro x64 1909 (18363.657)

**Comment by msuperina** [comment]
@ColinEberhardt I can look into that tomorrow

**Comment by ColinEberhardt** [comment]
Fixed, thanks to @jbradshaw-scottlogic :+1:

**Comment by tiadaguru** [comment]
My apologies for the delayed reply.

A big thank you to @jbradshaw-scottlogic and @ColinEberhardt for this fix; I can confirm the new update 3.3.1 has completely solved this issue.

**Comment by ColinEberhardt** [comment]
Nice one - thanks for getting back to us @tiadaguru
