### ISSUE TITLE
Broken page after adding applause button

### ISSUE THREAD

**Issue by azzamsa** [ColinEberhardt/applause-button#40]
Hi,

We had broken page [after adding](https://github.com/Pelican-Elegant/elegant/pull/541/files) applause button. This is the "broken page" [looks like](https://elegant.oncrashreboot.com/applause-button). and [this is](https://github.com/Pelican-Elegant/elegant/issues/543#issuecomment-562912123) the related issue.

Do you have any hints for us?

Thank you for applause button.

**Comment by bhadaway** [comment]
Make sure to wrap the code with a div or similar like so:

`<div><applause-button /></div>`

My best guess as to why this happens in some browsers is because `applause-button` isn't official HTML, and therefore unrecognized, causing it to not closer properly.

**Comment by azzamsa** [comment]
Sorry, but I don't use it anymore.
Feel free to reopen the issue if needed. But I can't provide any further debug info.
