### ISSUE TITLE
No longer page-specific

### ISSUE THREAD

**Issue by glendeni** [ColinEberhardt/applause-button#78]
I have script on 4 different pages.  At one time I know there were different counts on each page.  But now, all have same number and clicking on one changes count on all pages.

 https://bigsurtrailmap.net/hiking-basics.html
 https://bigsurtrailmap.net/wilderness-places-to-visit.html
 https://bigsurtrailmap.net/backpack-suggestions.html
 https://bigsurtrailmap.net/wilderness-tours.html

**Comment by chriswilty** [comment]
We cannot access those pages outside of USA, so cannot check how you are using this component. Remember that the `url` attribute you use on your component instances must be unique for each one.

Please register a new issue if this is still a problem.
